import 'package:drift/drift.dart';

/// Local cache of the `item_tags`/`tags` join (see
/// infra/supabase/migrations/0001_init.sql and 0016_replace_tags_entities_atomic.sql)
/// — one row per (item, tag name) pair. Read-only from this device's point
/// of view: tags are entirely AI-generated by the backend pipeline
/// (`tagging_service.py`), never edited locally, so unlike `LocalItems`
/// there's no `syncStatus`/pending-edit case here — `SyncService._pullRemote`
/// just replaces the whole cache with the server's current set each sync.
///
/// No `userId` column, same reasoning as `LocalCollectionItems`: scoping
/// goes through a join against `LocalItems` (which does carry one) rather
/// than duplicating it here. Added for P2-07
/// (docs/requirements-audit-2026-09-13.md) so `LocalSearchDataSource` can
/// match a query against an item's tags without a network round trip.
class LocalTags extends Table {
  TextColumn get itemId => text()();
  TextColumn get name => text()();

  @override
  Set<Column> get primaryKey => {itemId, name};
}
